apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: python-app-netpol
  namespace: github-copilot-ns
  labels:
    app: python-app
    environment: production
spec:
  podSelector:
    matchLabels:
      app: python-app
  policyTypes:
  - Ingress
  - Egress
  
  # Ingress rules - Allow incoming traffic on port 8080
  ingress:
  - from:
    - namespaceSelector: {}
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080
  
  # Egress rules - Allow necessary outbound traffic
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  
  # Allow HTTPS for external API calls if needed
  - to: []
    ports:
    - protocol: TCP
      port: 443
  
  # Allow HTTP for health checks and internal communication
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 8080
