apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: python-app-pdb
  namespace: github-copilot-ns
  labels:
    app: python-app
    environment: production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: python-app
